### ISSUE TITLE
Getting started on Ubuntu 16.04

### ISSUE THREAD

**Issue by orschiro** [jml/undistract-me#37]
Dear @jml,

Thank you so much for this excellent project!

I installed undistract-me as follows:

`sudo apt install undistract-me`. 

It installed the following version:

```
ii  undistract-me                                        0.1.0+git20130402+3a9144bc1f-1                              all          Notifies user when long-running terminal commands complete via libnotify
```

However, I am not receiving any notification on commands that take longer than 10 seconds. 

What else do I need to configure?

Thankfully,

-Robert

**Comment by jml** [comment]
Hi!

You need to either log out & log in again, or you need to run:

```
. /etc/profile.d/undistract-me.sh
```

In your prompt. 

jml

**Comment by orschiro** [comment]
Thank you!

So I tried the following as a test:

```
orschiro@x230:~$ . /etc/profile.d/undistract-me.sh
orschiro@x230:~$ sleep 15s
```

However, it does not produce any notification either. Shouldn't the sleep command of 15 seconds produce one?

Warmly,

-Robert

**Comment by jml** [comment]
It should. Are you using bash?

**Comment by orschiro** [comment]
Yes, I am using the default Bash of Ubuntu 16.04.

**Comment by orschiro** [comment]
Hello again, 

It's been a while. Now testing undistract-me on Ubuntu MATE 17.10 Alpha 2. 

I think the README is outdated. It says:

> Then run a login shell: start a whole new Gnome Terminal, run bash --login or log out then log in again.

Tried exactly this after installing undistract-me from the Ubuntu repos but it's not working. 

Did something change or shall we add @fotonmoton suggestion to the README.

**Comment by jml** [comment]
Nothing has changed in undistract-me. It's possible that the mechanism the package uses to install it as something that is sourced by everyone's bashrc no longer works.

No objections to adding @fotonmoton's suggestion to README.

**Comment by orschiro** [comment]
See https://github.com/jml/undistract-me/pull/46.

**Comment by chandraBatre** [comment]
Huge thanks to @photonmoton.
I confirm that their solution worked great.
I added:
source /etc/profile.d/undistract-me.sh
into the end of my .profile
and ran:
$ . ~/.profile
and the apt update command worked notified me properly.
Also for the record I am using Ubuntu 18.04LTS on a MacBook 2009.
